CDE-14 Repository selection step
MetaCell/cde-mapper pull request #7
Opened 2024-01-01 11:23 UTC by Aiga115

Issue #CDE-14
Problem:  Repository selection step
Solution: Created UI for repository selection step
<img width="1063" alt="image" src="https://github.com/MetaCell/cde-mapper/assets/67194168/1fb36dd1-c7c1-4a3a-9873-73deb340cf0c">

2024-01-03 14:51 UTC, vidhya-metacell requested changes
@Aiga115 For the tabs in the modal, i have already added them in my other PR. Feel free to update from there

2024-01-03 14:54 UTC, vidhyalongani commented on lib/components/steps/StepTwo.tsx
> +                <Stack alignItems="center" justifyContent="center" sx={{mx: 3, my: 6}}>
@Aiga115 this will be stepone not two, suggestions would be step one

2024-01-08 11:17 UTC, vidhya-metacell requested changes
@Aiga115 things looks good. Just few fixes are required

- this whole box should be clickable not just the text

- also the height in figms for the box is 52

<img width="333" alt="Screen Shot 2024-01-08 at 12 14 32 PM" src="https://github.com/MetaCell/cde-mapper/assets/71261494/f9b6f7db-aff2-4ef2-9db7-3072ad4aada9">

- No padding is required in this one
<img width="428" alt="Screen Shot 2024-01-08 at 12 17 11 PM" src="https://github.com/MetaCell/cde-mapper/assets/71261494/7ad7dd5b-f6c4-446a-b843-5362423cb62b">

2024-01-08 11:19 UTC, vidhya-metacell commented on lib/components/steps/StepOne.tsx
> +                                Can’t find the repository you’re looking for? Contact us{' '}
@Aiga115 this text should be some link inside the typography

2024-01-08 17:47 UTC, zsinnema commented
@Aiga115 there are some merge conflicts, can you please solve them? Thanks!

2024-01-09 14:29 UTC, vidhyalongani approved these changes
@Aiga115 looks good.
@zsinnema this can be merged

2024-01-10 14:45 UTC, zsinnema commented
thanks @vidhya-metacell

2024-01-10 14:45 UTC, merged